name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "cloning the code"

  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Building using docker"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Testing the code"

  deploy:
    needs: [test,build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the code
        run: echo "deploying the code"
