name: CICD

on: workflow_dispatch

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: clone the code
        run: echo "cloning the code"
  build:
      runs-on: ubuntu-latest
    steps:
      - name: Build using docker
        run: echo "Building using docker"
  test:
      runs-on: ubuntu-latest
    steps:
      - name: Test the code
        run: echo "Testing the code"
deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploying the code
        run: echo "deploying the code"



  
